/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arraypadaformneatbean;

/**
 *
 * @author Iqbal Albana
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jconadokt = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pilih Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 80, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel2.setText("Ayo dipilih-dipilih Dokter e Dokter e");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 350, 60);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. Farras Yassar", "DR. Anisa Putri ", "DR. Harun Fajar " }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(130, 70, 140, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setLayout(null);

        jLabel3.setText("Dokter Spesialis");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 260, 100, 20);

        jLabel5.setText("Usia");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 80, 60, 20);

        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 110, 80, 20);

        jLabel7.setText("Golongan Darah");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 140, 90, 20);

        jLabel8.setText("Status");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 170, 60, 20);

        jLabel9.setText("Kewarganegaraan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 200, 100, 20);

        jLabel10.setText("Waktu Praktek");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 230, 90, 20);

        jLabel11.setText("Nama");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 20, 60, 20);

        jLabel12.setText("Alamat");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 50, 60, 20);

        jtxtwaktu.setEditable(false);
        jPanel1.add(jtxtwaktu);
        jtxtwaktu.setBounds(130, 220, 150, 30);

        jtxtusia.setEditable(false);
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(130, 70, 150, 30);

        jtxtjenis.setEditable(false);
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(130, 100, 150, 30);

        jtxtgol.setEditable(false);
        jPanel1.add(jtxtgol);
        jtxtgol.setBounds(130, 130, 150, 30);

        jtxtstatus.setEditable(false);
        jPanel1.add(jtxtstatus);
        jtxtstatus.setBounds(130, 160, 150, 30);

        jtxtkewar.setEditable(false);
        jPanel1.add(jtxtkewar);
        jtxtkewar.setBounds(130, 190, 150, 30);

        jtxtspesial.setEditable(false);
        jPanel1.add(jtxtspesial);
        jtxtspesial.setBounds(130, 250, 150, 30);

        jtxtnama.setEditable(false);
        jtxtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(130, 10, 150, 30);

        jtxtalamat.setEditable(false);
        jtxtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtalamatActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(130, 40, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 110, 310, 300);

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\PHOTOSHOP\\Background1.jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-200, -60, 680, 640);

        setBounds(0, 0, 374, 479);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnamaActionPerformed

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){ 
            jtxtnama.setText("DR. Farras Yassar "); 
            jtxtalamat.setText("Jl. Surabaya 16, Malang"); 
            jtxtusia.setText("20 Tahun"); 
            jtxtjenis.setText("Laki-Laki"); 
            jtxtgol.setText("A"); 
            jtxtstatus.setText("Belum Menikah "); 
            jtxtkewar.setText("Indonesia"); 
            jtxtspesial.setText("Dokter Umum"); 
            jtxtwaktu.setText(" Pagi (07.00-15.00)"); 
        } 
        else 
        if(jconadokt.getSelectedItem().equals("DR. Anisa Putri ")){ 
            jtxtnama.setText("DR. Anisa Putri"); 
            jtxtalamat.setText("Jl. Veteran 3, Malang"); 
            jtxtusia.setText("20 Tahun"); 
            jtxtjenis.setText("Perempuan"); 
            jtxtgol.setText("O"); 
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia"); 
            jtxtspesial.setText("Dokter Gigi"); 
            jtxtwaktu.setText(" Sore (16.00-22.00)"); 
        } 
        else 
        if(jconadokt.getSelectedItem().equals("DR. Harun Fajar ")){ 
            jtxtnama.setText("DR. Harun Fajar "); 
            jtxtalamat.setText("Jl. Bandung 9, Malang"); 
            jtxtusia.setText("20 Tahun"); 
            jtxtjenis.setText("Laki-Laki"); 
            jtxtgol.setText("B"); 
            jtxtstatus.setText("Belum Menikah"); 
            jtxtkewar.setText("Indonesia"); 
            jtxtspesial.setText("Dokter Gizi"); 
            jtxtwaktu.setText(" Malam (22.00-06.00)"); 
        } 
    }//GEN-LAST:event_jconadoktActionPerformed

    private void jtxtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtalamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
